### ISSUE TITLE
Change preview screenshot

### ISSUE THREAD

**Issue by luizpicolo** [luizpicolo/rails_admin_featured_content#14]

**Comment by gabrielmedina** [comment]
Hi my friend. This screenshot is approved?

![featured-min](https://cloud.githubusercontent.com/assets/2979365/20011773/7b5a7544-a28b-11e6-950c-3b47f4556b98.jpg)

**Comment by luizpicolo** [comment]
Approved :bear: with :hankey: in the :nose:

**Comment by gabrielmedina** [comment]
hahahahaha! nice 🐻

**Comment by gabrielmedina** [comment]
Finished #15
