### ISSUE TITLE
Improve the images of navigation

### ISSUE THREAD

**Issue by gabrielmedina** [luizpicolo/rails_admin_featured_content#5]
Design better images to navigation of sidebar.

- [x] Improve images current;
- [x] Add image to list of 4 items;

**Comment by ShreyaSa** [comment]
I'll be looking into this, okay?

**Comment by hahaveryfun** [comment]
Looking into

**Comment by gabrielmedina** [comment]
Hi @ShreyaSa I created this issue only for documentation. I'm finished this :/

**Comment by gabrielmedina** [comment]
Finished! 🎉 Check this on: https://github.com/luizpicolo/rails_admin_featured_content/pull/7
